Bash can't deal with Numbers longer than 19 chars See FOO=0; for x in $(seq 1 25); do FOO=${FOO}1 ; [ $FOO -ge 1 ] || echo "NOT OK ${#FOO}" ; done for more."

diff --git a/statistical b/statistical
--- a/statistical
+++ b/statistical
@@ -29,6 +29,14 @@ for data in $SUM; do
         exit 1
     fi
 
+    # Bash couldn't handle values with more than 19 numbers
+    # Values longer than 19 will be transformed into strings.
+    # String could not be graphed :) 
+    if [[ ${#VALUE} -gt 19 ]]; then 
+        echo "Error: Bash couldn't handle values with more than 19 numbers. Sorry."
+        exit 1
+    fi
+
     # Doing the right formatting for a global 
     # tabulator spaces work
     if [ ${#KEY} -gt 23 ]; then 
